<?php
/**
 * Plugin Name: BW Creator Store Builder
 * Description: Adds a creator-side checklist for standard product templates and syncs generated store products for each creator.
 * Version: 1.0.0
 * Author: You
 * License: GPL-2.0+
 */

if (!defined('ABSPATH')) exit;

class BW_Creator_Store_Builder {
  const CPT_CREATOR = 'bw_creator';
  const TAX_PRODUCT_CAT = 'product_cat';

  const META_CREATOR_CAT = '_bw_creator_wc_category';
  const META_IS_TEMPLATE = '_bw_is_template';
  const META_TEMPLATE_ID = '_bwcsb_template_id';
  const META_CREATOR_ID  = '_bwcsb_creator_id';
  const META_MANAGED     = '_bwcsb_managed_product';
  const NONCE            = 'bw_creator_store_builder_nonce';

  public function __construct(){
    add_action('add_meta_boxes', [$this, 'add_meta_box']);
    add_action('save_post_' . self::CPT_CREATOR, [$this, 'save_creator_products'], 30);
  }

  public function add_meta_box(){
    add_meta_box(
      'bw_creator_store_builder',
      __('Store Product Builder', 'bw'),
      [$this, 'render_meta_box'],
      self::CPT_CREATOR,
      'normal',
      'high'
    );
  }

  public function render_meta_box($post){
    if (!current_user_can('edit_post', $post->ID)) {
      return;
    }

    wp_nonce_field(self::NONCE, self::NONCE);

    $category_slug = get_post_meta($post->ID, self::META_CREATOR_CAT, true);
    if ($category_slug === '') {
      $category_slug = sanitize_title($post->post_name ?: $post->post_title);
    }

    $templates = $this->get_templates();
    $selected_templates = $this->get_selected_template_ids($post->ID);
    $category = $category_slug !== '' ? get_term_by('slug', $category_slug, self::TAX_PRODUCT_CAT) : null;
    $managed_count = $this->count_managed_products($post->ID);
    ?>
    <style>
      .bwcsb-grid{display:grid;gap:16px}
      .bwcsb-help{margin:0;color:#50575e}
      .bwcsb-field input[type=text]{width:100%;max-width:420px}
      .bwcsb-list{max-height:320px;overflow:auto;border:1px solid #dcdcde;border-radius:8px;padding:12px;background:#fff}
      .bwcsb-item{display:flex;align-items:flex-start;gap:8px;margin:0 0 10px}
      .bwcsb-item:last-child{margin-bottom:0}
      .bwcsb-item small{display:block;color:#50575e}
      .bwcsb-badge{display:inline-block;margin-left:8px;padding:2px 8px;border-radius:999px;background:#edf7ed;color:#166534;font-size:11px;font-weight:600;vertical-align:middle}
    </style>
    <div class="bwcsb-grid">
      <p class="bwcsb-help"><?php esc_html_e('Pick the standard products this creator should have in their store. Checked items will be created or published for this creator; unchecked items generated by this tool will be saved as drafts.', 'bw'); ?></p>

      <div class="bwcsb-field">
        <label for="bwcsb_creator_category"><strong><?php esc_html_e('Store Category Slug', 'bw'); ?></strong></label>
        <input id="bwcsb_creator_category" name="bwcsb_creator_category" type="text" value="<?php echo esc_attr($category_slug); ?>" placeholder="<?php esc_attr_e('creator-name', 'bw'); ?>">
        <p class="bwcsb-help"><?php esc_html_e('This WooCommerce category is used to group the creator’s products and also syncs the creator landing product category slug.', 'bw'); ?></p>
        <?php if ($category && !is_wp_error($category)): ?>
          <p class="bwcsb-help"><?php echo esc_html(sprintf(__('Current category: %s', 'bw'), $category->name)); ?><span class="bwcsb-badge"><?php echo esc_html(sprintf(_n('%d managed product', '%d managed products', $managed_count, 'bw'), $managed_count)); ?></span></p>
        <?php endif; ?>
      </div>

      <div>
        <strong><?php esc_html_e('Standard Products', 'bw'); ?></strong>
        <div class="bwcsb-list">
          <?php if ($templates): ?>
            <?php foreach ($templates as $template): ?>
              <?php
                $template_id = (int) $template->ID;
                $is_selected = in_array($template_id, $selected_templates, true);
              ?>
              <label class="bwcsb-item">
                <input type="checkbox" name="bwcsb_template_ids[]" value="<?php echo $template_id; ?>" <?php checked($is_selected); ?>>
                <span>
                  <strong><?php echo esc_html($template->post_title); ?></strong>
                  <small><?php echo esc_html(sprintf(__('Template ID %d', 'bw'), $template_id)); ?></small>
                </span>
              </label>
            <?php endforeach; ?>
          <?php else: ?>
            <p class="bwcsb-help"><?php esc_html_e('No product templates found yet. Mark common products as templates in the Product edit screen first.', 'bw'); ?></p>
          <?php endif; ?>
        </div>
      </div>
    </div>
    <?php
  }

  public function save_creator_products($post_id){
    if (!isset($_POST[self::NONCE]) || !wp_verify_nonce($_POST[self::NONCE], self::NONCE)) return;
    if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
    if (!current_user_can('edit_post', $post_id)) return;
    if (!taxonomy_exists(self::TAX_PRODUCT_CAT) || !post_type_exists('product')) return;

    $creator = get_post($post_id);
    if (!$creator || $creator->post_type !== self::CPT_CREATOR) return;

    $requested_slug = sanitize_title(wp_unslash($_POST['bwcsb_creator_category'] ?? ''));
    $category_slug = $requested_slug ?: sanitize_title($creator->post_name ?: $creator->post_title);
    if ($category_slug === '') return;

    $category_id = $this->ensure_category($category_slug, $creator->post_title);
    if (!$category_id) return;

    // Cloning and publishing live storefront products requires product-management
    // rights, not merely permission to edit the creator post.
    if (!current_user_can('publish_products')) return;

    update_post_meta($post_id, self::META_CREATOR_CAT, $category_slug);

    $selected_template_ids = array_values(array_unique(array_filter(array_map('intval', (array) ($_POST['bwcsb_template_ids'] ?? [])))));
    $existing_products = $this->get_managed_products_by_template($post_id);

    foreach ($selected_template_ids as $template_id) {
      $template = get_post($template_id);
      if (!$template || $template->post_type !== 'product') continue;
      // Only clone products explicitly marked as reusable templates — never an
      // arbitrary product ID smuggled in via the POSTed list.
      if (get_post_meta($template_id, self::META_IS_TEMPLATE, true) !== '1') continue;

      if (!isset($existing_products[$template_id])) {
        $new_product_id = $this->duplicate_product($template_id);
        if (!$new_product_id) continue;

        $existing_products[$template_id] = $new_product_id;
        update_post_meta($new_product_id, self::META_TEMPLATE_ID, $template_id);
        update_post_meta($new_product_id, self::META_CREATOR_ID, $post_id);
        update_post_meta($new_product_id, self::META_MANAGED, '1');
        delete_post_meta($new_product_id, self::META_IS_TEMPLATE);
      }

      $this->sync_generated_product($existing_products[$template_id], $category_id, 'publish');
    }

    foreach ($existing_products as $template_id => $product_id) {
      if (in_array((int) $template_id, $selected_template_ids, true)) {
        continue;
      }

      $this->sync_generated_product($product_id, $category_id, 'draft');
    }
  }

  private function get_templates(){
    return get_posts([
      'post_type' => 'product',
      'post_status' => ['publish', 'draft', 'private'],
      'posts_per_page' => -1,
      'meta_key' => self::META_IS_TEMPLATE,
      'meta_value' => '1',
      'orderby' => 'title',
      'order' => 'ASC',
    ]);
  }

  private function get_selected_template_ids($creator_id){
    $product_ids = get_posts([
      'post_type' => 'product',
      'post_status' => ['publish', 'draft', 'private', 'pending', 'future'],
      'posts_per_page' => -1,
      'fields' => 'ids',
      'meta_query' => [
        [
          'key' => self::META_CREATOR_ID,
          'value' => (string) $creator_id,
        ],
        [
          'key' => self::META_MANAGED,
          'value' => '1',
        ],
      ],
    ]);

    if (!$product_ids) {
      return [];
    }

    $selected = [];
    foreach ($product_ids as $product_id) {
      if (get_post_status($product_id) !== 'publish') {
        continue;
      }

      $template_id = (int) get_post_meta($product_id, self::META_TEMPLATE_ID, true);
      if ($template_id > 0) {
        $selected[] = $template_id;
      }
    }

    return array_values(array_unique($selected));
  }

  private function get_managed_products_by_template($creator_id){
    $product_ids = get_posts([
      'post_type' => 'product',
      'post_status' => ['publish', 'draft', 'private', 'pending', 'future'],
      'posts_per_page' => -1,
      'fields' => 'ids',
      'meta_query' => [
        [
          'key' => self::META_CREATOR_ID,
          'value' => (string) $creator_id,
        ],
        [
          'key' => self::META_MANAGED,
          'value' => '1',
        ],
      ],
    ]);

    $mapped = [];
    foreach ($product_ids as $product_id) {
      $template_id = (int) get_post_meta($product_id, self::META_TEMPLATE_ID, true);
      if ($template_id > 0 && !isset($mapped[$template_id])) {
        $mapped[$template_id] = (int) $product_id;
      }
    }

    return $mapped;
  }

  private function count_managed_products($creator_id){
    $products = $this->get_managed_products_by_template($creator_id);
    return count($products);
  }

  private function ensure_category($slug, $creator_name){
    $existing = get_term_by('slug', $slug, self::TAX_PRODUCT_CAT);
    if ($existing && !is_wp_error($existing)) {
      return (int) $existing->term_id;
    }

    $term_name = $creator_name !== '' ? $creator_name : ucwords(str_replace('-', ' ', $slug));
    $created = wp_insert_term($term_name, self::TAX_PRODUCT_CAT, ['slug' => $slug]);
    if (is_wp_error($created)) {
      return 0;
    }

    return (int) $created['term_id'];
  }

  private function sync_generated_product($product_id, $category_id, $status){
    if (!$product_id || !$category_id) return;

    wp_set_object_terms($product_id, [$category_id], self::TAX_PRODUCT_CAT, true);

    $current_status = get_post_status($product_id);
    if ($current_status !== $status) {
      wp_update_post([
        'ID' => $product_id,
        'post_status' => $status,
      ]);
    }
  }

  private function duplicate_product($template_id){
    $new_id = 0;

    if (class_exists('WC_Admin_Duplicate_Product')) {
      $product = wc_get_product($template_id);
      if ($product) {
        $new_id = \WC_Admin_Duplicate_Product::product_duplicate($product);
      }
    }

    if ($new_id) {
      return (int) $new_id;
    }

    $post = get_post($template_id);
    if (!$post || $post->post_type !== 'product') {
      return 0;
    }

    $new_id = wp_insert_post([
      'post_author' => get_current_user_id(),
      'post_content' => $post->post_content,
      'post_excerpt' => $post->post_excerpt,
      'post_status' => 'draft',
      'post_title' => $post->post_title,
      'post_type' => 'product',
    ]);

    if (!$new_id) {
      return 0;
    }

    $all_meta = get_post_meta($template_id);
    foreach ($all_meta as $key => $values) {
      if ($key === self::META_IS_TEMPLATE) continue;

      foreach ($values as $value) {
        add_post_meta($new_id, $key, maybe_unserialize($value));
      }
    }

    $thumbnail_id = get_post_thumbnail_id($template_id);
    if ($thumbnail_id) {
      set_post_thumbnail($new_id, $thumbnail_id);
    }

    $taxonomies = get_object_taxonomies('product');
    foreach ($taxonomies as $taxonomy) {
      $terms = wp_get_object_terms($template_id, $taxonomy, ['fields' => 'ids']);
      if (!is_wp_error($terms)) {
        wp_set_object_terms($new_id, $terms, $taxonomy);
      }
    }

    return (int) $new_id;
  }
}

new BW_Creator_Store_Builder();
